# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 22:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=400)),
                ('picLink', models.ImageField(blank=True, upload_to='place_images')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('placeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagText', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('placeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=400)),
                ('picLink', models.ImageField(blank=True, upload_to='trip_images')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripPoint', models.IntegerField()),
                ('placeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Place')),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagText', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default="Hello it's me!", max_length=400)),
                ('livesIn', models.CharField(default='Somewhere', max_length=20)),
                ('rep', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='triptag',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AddField(
            model_name='tripreview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AddField(
            model_name='trip',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AddField(
            model_name='placetag',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AddField(
            model_name='place',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
    ]
