# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Place'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommendedTrip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Trip'),
        ),
    ]
