# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='picLink',
            field=models.ImageField(blank=True, upload_to='place_images'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='picLink',
            field=models.ImageField(blank=True, upload_to='trip_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='Hello is me', max_length=400),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='livesIn',
            field=models.CharField(default='Somewhere', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
