# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='placeholdr.UserProfile')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile')),
            ],
        ),
    ]
