# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0002_auto_20180320_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='livesIn',
            field=models.CharField(default='The Default Place', max_length=20),
        ),
    ]
