# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0003_auto_20180327_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuser',
            name='following',
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='userId',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='placeholdr.UserProfile'),
        ),
        migrations.DeleteModel(
            name='FollowUser',
        ),
    ]
