# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0006_auto_20180313_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triptag',
            name='placeId',
        ),
        migrations.AddField(
            model_name='triptag',
            name='tripId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placeholdr.Trip'),
            preserve_default=False,
        ),
    ]
