# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0008_auto_20180316_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/profile_images/'),
        ),
    ]
