# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0009_auto_20180316_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AlterField(
            model_name='placetag',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AlterField(
            model_name='tripreview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AlterField(
            model_name='triptag',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeholdr.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
