# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeholdr', '0010_auto_20180316_1555'),
        ('placeholdr', '0010_auto_20180316_1524'),
    ]

    operations = [
    ]
